"use client";

import { useState, useEffect } from "react";
import { motion } from "framer-motion";

const fade = (d = 0) => ({
  hidden: { opacity: 0, y: 12 },
  visible: { opacity: 1, y: 0, transition: { duration: 0.5, delay: d } },
});

const COLLECTION_NAME = "app_users";

const SCHEMA_FIELDS = [
  { field: "_id",          type: "ObjectId",  note: "Auto-generated by MongoDB" },
  { field: "clerkUserId",  type: "String",    note: "Clerk user ID — links record to authenticated user" },
  { field: "name",         type: "String",    note: "Customer or resource name" },
  { field: "email",        type: "String",    note: "Contact email (unique index)" },
  { field: "plan",         type: "String",    note: "Tier within the client's app" },
  { field: "pageViews",    type: "Number",    note: "Total page views by this user" },
  { field: "sessionCount", type: "Number",    note: "Total sessions" },
  { field: "firstSeenAt",  type: "Date",      note: "ISO 8601 timestamp" },
  { field: "lastSeenAt",   type: "Date",      note: "Auto-updated on activity" },
  { field: "metadata",     type: "Object",    note: "Flexible — custom fields you define" },
];

interface AppUser {
  _id: string;
  name: string;
  email: string;
  plan?: string;
  pageViews: number;
  sessionCount: number;
  firstSeenAt: string;
  lastSeenAt: string;
  metadata?: Record<string, unknown>;
}

export default function DataPage() {
  const [users, setUsers] = useState<AppUser[]>([]);
  const [loading, setLoading] = useState(true);
  const [search, setSearch] = useState("");
  const [view, setView] = useState<"table" | "schema">("table");

  useEffect(() => {
    fetch("/api/me/users")
      .then((r) => r.json())
      .then((data) => { if (Array.isArray(data)) setUsers(data); })
      .catch(() => null)
      .finally(() => setLoading(false));
  }, []);

  const filtered = users.filter((u) =>
    u.name.toLowerCase().includes(search.toLowerCase()) ||
    u.email.toLowerCase().includes(search.toLowerCase())
  );

  return (
    <div className="px-8 py-8 max-w-5xl">
      {/* Header */}
      <motion.div variants={fade(0)} initial="hidden" animate="visible" className="mb-8">
        <div className="flex items-start justify-between flex-wrap gap-4">
          <div>
            <h1 className="text-xl font-semibold text-white">My Data</h1>
            <p className="text-sm text-white/40 mt-1">
              App users stored in your personal MongoDB collection.
            </p>
          </div>
          {!loading && (
            <div className={`flex items-center gap-2 border rounded-xl px-4 py-2.5 ${
              users.length > 0
                ? "bg-emerald-400/[0.08] border-emerald-400/20"
                : "bg-blue-400/[0.08] border-blue-400/20"
            }`}>
              <span className={`w-2 h-2 rounded-full shrink-0 ${users.length > 0 ? "bg-emerald-400" : "bg-blue-400"}`} />
              <span className={`text-xs font-medium ${users.length > 0 ? "text-emerald-400" : "text-blue-400"}`}>
                {users.length > 0 ? `${users.length} record${users.length !== 1 ? "s" : ""}` : "No users yet"}
              </span>
            </div>
          )}
        </div>
      </motion.div>

      {/* Collection info */}
      <motion.div
        variants={fade(0.05)}
        initial="hidden"
        animate="visible"
        className="grid sm:grid-cols-3 gap-4 mb-8"
      >
        {[
          { label: "Collection",  value: COLLECTION_NAME,               mono: true,  color: "text-blue-400" },
          { label: "Documents",   value: loading ? "…" : users.length.toString(), mono: false, color: "text-white" },
          { label: "Total views", value: loading ? "…" : users.reduce((s, u) => s + (u.pageViews ?? 0), 0).toLocaleString(), mono: false, color: "text-emerald-400" },
        ].map(({ label, value, mono, color }) => (
          <div key={label} className="bg-white/[0.03] border border-white/[0.07] rounded-2xl p-5">
            <p className="text-xs text-white/40 mb-1.5">{label}</p>
            <p className={`text-sm font-bold ${color} ${mono ? "font-mono" : ""}`}>{value}</p>
          </div>
        ))}
      </motion.div>

      {/* View toggle */}
      <motion.div variants={fade(0.08)} initial="hidden" animate="visible" className="mb-5">
        <div className="flex gap-1.5 bg-white/[0.03] border border-white/[0.06] rounded-xl p-1 w-fit">
          {(["table", "schema"] as const).map((v) => (
            <button
              key={v}
              onClick={() => setView(v)}
              className={`relative px-4 py-1.5 rounded-lg text-xs font-medium capitalize transition-colors ${
                view === v ? "text-white" : "text-white/40 hover:text-white/60"
              }`}
            >
              {view === v && (
                <motion.div
                  layoutId="data-view-tab"
                  className="absolute inset-0 bg-white/[0.08] rounded-lg"
                  transition={{ type: "spring", stiffness: 400, damping: 30 }}
                />
              )}
              <span className="relative z-10">
                {v === "table" ? "📋 Documents" : "🗂 Schema"}
              </span>
            </button>
          ))}
        </div>
      </motion.div>

      {view === "table" ? (
        <motion.div variants={fade(0.1)} initial="hidden" animate="visible">
          {/* Search */}
          <div className="flex flex-wrap gap-3 mb-5">
            <div className="relative flex-1 min-w-[200px]">
              <svg className="absolute left-3 top-1/2 -translate-y-1/2 w-4 h-4 text-white/25" fill="none" stroke="currentColor" strokeWidth={2} viewBox="0 0 24 24">
                <circle cx="11" cy="11" r="8" /><line x1="21" y1="21" x2="16.65" y2="16.65" />
              </svg>
              <input
                type="text"
                placeholder="Search by name or email…"
                value={search}
                onChange={(e) => setSearch(e.target.value)}
                className="w-full bg-white/[0.04] border border-white/[0.08] rounded-xl pl-9 pr-4 py-2.5 text-sm text-white placeholder:text-white/25 outline-none focus:border-white/20 transition-colors"
              />
            </div>
          </div>

          {/* Table */}
          <div className="bg-white/[0.02] border border-white/[0.07] rounded-2xl overflow-hidden">
            <div className="grid grid-cols-[1fr_1.5fr_80px_80px_100px] gap-4 px-5 py-3 border-b border-white/[0.06] text-[11px] font-semibold uppercase tracking-widest text-white/25">
              <span>Name</span>
              <span>Email</span>
              <span>Plan</span>
              <span className="text-right">Views</span>
              <span className="text-right">Last seen</span>
            </div>
            {loading ? (
              <div className="px-5 py-12 text-center text-white/30 text-sm">Loading…</div>
            ) : filtered.length === 0 ? (
              <div className="px-5 py-12 text-center">
                <p className="text-white/30 text-sm">
                  {users.length === 0 ? "No users yet — they will appear here once people sign in to your app." : "No results for that search."}
                </p>
              </div>
            ) : (
              filtered.map((user, i) => (
                <div
                  key={user._id}
                  className={`grid grid-cols-[1fr_1.5fr_80px_80px_100px] gap-4 px-5 py-3.5 items-center hover:bg-white/[0.02] transition-colors ${
                    i < filtered.length - 1 ? "border-b border-white/[0.05]" : ""
                  }`}
                >
                  <div>
                    <p className="text-sm font-medium text-white">{user.name}</p>
                    <p className="text-[10px] text-white/25 font-mono mt-0.5 truncate">{user._id}</p>
                  </div>
                  <p className="text-sm text-white/60 truncate">{user.email}</p>
                  <span className="text-[10px] font-semibold px-2 py-0.5 rounded-full text-center bg-violet-400/10 text-violet-400 truncate">
                    {user.plan ?? "free"}
                  </span>
                  <p className="text-sm font-semibold text-right text-white/60">
                    {(user.pageViews ?? 0).toLocaleString()}
                  </p>
                  <p className="text-xs text-white/40 text-right">
                    {new Date(user.lastSeenAt).toLocaleDateString("en-US", { month: "short", day: "numeric" })}
                  </p>
                </div>
              ))
            )}
          </div>
        </motion.div>
      ) : (
        /* Schema view */
        <motion.div variants={fade(0.1)} initial="hidden" animate="visible">
          <div className="bg-white/[0.02] border border-white/[0.07] rounded-2xl overflow-hidden">
            <div className="grid grid-cols-[140px_100px_1fr] gap-4 px-5 py-3 border-b border-white/[0.06] text-[11px] font-semibold uppercase tracking-widest text-white/25">
              <span>Field</span>
              <span>Type</span>
              <span>Description</span>
            </div>
            {SCHEMA_FIELDS.map((field, i) => (
              <div
                key={field.field}
                className={`grid grid-cols-[140px_100px_1fr] gap-4 px-5 py-3.5 items-start hover:bg-white/[0.02] transition-colors ${
                  i < SCHEMA_FIELDS.length - 1 ? "border-b border-white/[0.04]" : ""
                }`}
              >
                <code className="text-sm font-mono text-[#FF6B61]">{field.field}</code>
                <span className="text-xs font-semibold text-blue-400 bg-blue-400/10 px-2 py-0.5 rounded-full w-fit">
                  {field.type}
                </span>
                <p className="text-sm text-white/45">{field.note}</p>
              </div>
            ))}
          </div>
          <p className="text-xs text-white/20 mt-3 text-center">
            Schema is customizable — fields can be added or modified to fit your business model.
          </p>
        </motion.div>
      )}
    </div>
  );
}
