"use client";

import { useState } from "react";
import { motion } from "framer-motion";

const fade = (d = 0) => ({
  hidden: { opacity: 0, y: 12 },
  visible: { opacity: 1, y: 0, transition: { duration: 0.5, delay: d } },
});

/* ─── Mock collection schema (ready to wire to real Atlas data) ── */
const COLLECTION_NAME = "your_business_data";

const SCHEMA_FIELDS = [
  { field: "_id",        type: "ObjectId",  note: "Auto-generated by MongoDB" },
  { field: "userId",     type: "String",    note: "Clerk user ID — links record to authenticated user" },
  { field: "name",       type: "String",    note: "Customer or resource name" },
  { field: "email",      type: "String",    note: "Contact email" },
  { field: "status",     type: "String",    note: "active | inactive | pending" },
  { field: "plan",       type: "String",    note: "free | pro | enterprise" },
  { field: "revenue",    type: "Number",    note: "Lifetime revenue from this record (USD)" },
  { field: "createdAt",  type: "Date",      note: "ISO 8601 timestamp" },
  { field: "updatedAt",  type: "Date",      note: "Auto-updated on write" },
  { field: "metadata",   type: "Object",    note: "Flexible — custom fields you define" },
];

/* ─── Mock documents (placeholder until DB wired) ─────────────── */
const MOCK_DOCS = [
  { _id: "64a1f2c...", userId: "user_2abc", name: "Jane Doe",     email: "jane@example.com",  status: "active",   plan: "pro",        revenue: 348,  createdAt: "2026-03-01" },
  { _id: "64a1f3d...", userId: "user_3def", name: "Bob Smith",    email: "bob@example.com",   status: "active",   plan: "pro",        revenue: 174,  createdAt: "2026-03-08" },
  { _id: "64a1f4e...", userId: "user_4ghi", name: "Sara Lee",     email: "sara@example.com",  status: "pending",  plan: "free",       revenue: 0,    createdAt: "2026-03-15" },
  { _id: "64a1f5f...", userId: "user_5jkl", name: "Mike Torres",  email: "mike@example.com",  status: "active",   plan: "enterprise", revenue: 980,  createdAt: "2026-03-20" },
  { _id: "64a1f6g...", userId: "user_6mno", name: "Priya Patel",  email: "priya@example.com", status: "inactive", plan: "free",       revenue: 0,    createdAt: "2026-03-25" },
  { _id: "64a1f7h...", userId: "user_7pqr", name: "Chris Nguyen", email: "chris@example.com", status: "active",   plan: "pro",        revenue: 522,  createdAt: "2026-03-28" },
];

const STATUS_CLS: Record<string, string> = {
  active:   "bg-emerald-400/10 text-emerald-400",
  inactive: "bg-white/[0.05] text-white/30",
  pending:  "bg-amber-400/10 text-amber-400",
};

const PLAN_CLS: Record<string, string> = {
  free:       "bg-white/[0.05] text-white/40",
  pro:        "bg-violet-400/10 text-violet-400",
  enterprise: "bg-[#FF6B61]/10 text-[#FF6B61]",
};

export default function DataPage() {
  const [search, setSearch] = useState("");
  const [statusFilter, setStatusFilter] = useState<string>("all");
  const [view, setView] = useState<"table" | "schema">("table");

  const filtered = MOCK_DOCS.filter((doc) => {
    const matchSearch =
      doc.name.toLowerCase().includes(search.toLowerCase()) ||
      doc.email.toLowerCase().includes(search.toLowerCase());
    const matchStatus = statusFilter === "all" || doc.status === statusFilter;
    return matchSearch && matchStatus;
  });

  return (
    <div className="px-8 py-8 max-w-5xl">
      {/* Header */}
      <motion.div variants={fade(0)} initial="hidden" animate="visible" className="mb-8">
        <div className="flex items-start justify-between flex-wrap gap-4">
          <div>
            <h1 className="text-xl font-semibold text-white">My Data</h1>
            <p className="text-sm text-white/40 mt-1">
              Your personal MongoDB collection.{" "}
              <span className="text-amber-400">Sample data shown</span> — live records will appear
              after database connection.
            </p>
          </div>
          <div className="flex items-center gap-2 bg-amber-400/[0.08] border border-amber-400/20 rounded-xl px-4 py-2.5">
            <span className="w-2 h-2 rounded-full bg-amber-400 shrink-0" />
            <span className="text-xs text-amber-400 font-medium">DB connection pending</span>
          </div>
        </div>
      </motion.div>

      {/* Collection info */}
      <motion.div
        variants={fade(0.05)}
        initial="hidden"
        animate="visible"
        className="grid sm:grid-cols-3 gap-4 mb-8"
      >
        {[
          { label: "Collection",     value: COLLECTION_NAME, mono: true, color: "text-blue-400" },
          { label: "Documents",      value: "6 (mock)",      mono: false, color: "text-white" },
          { label: "Total Revenue",  value: "$2,024 (mock)", mono: false, color: "text-emerald-400" },
        ].map(({ label, value, mono, color }) => (
          <div key={label} className="bg-white/[0.03] border border-white/[0.07] rounded-2xl p-5">
            <p className="text-xs text-white/40 mb-1.5">{label}</p>
            <p className={`text-sm font-bold ${color} ${mono ? "font-mono" : ""}`}>{value}</p>
          </div>
        ))}
      </motion.div>

      {/* View toggle */}
      <motion.div variants={fade(0.08)} initial="hidden" animate="visible" className="mb-5">
        <div className="flex gap-1.5 bg-white/[0.03] border border-white/[0.06] rounded-xl p-1 w-fit">
          {(["table", "schema"] as const).map((v) => (
            <button
              key={v}
              onClick={() => setView(v)}
              className={`relative px-4 py-1.5 rounded-lg text-xs font-medium capitalize transition-colors ${
                view === v ? "text-white" : "text-white/40 hover:text-white/60"
              }`}
            >
              {view === v && (
                <motion.div
                  layoutId="data-view-tab"
                  className="absolute inset-0 bg-white/[0.08] rounded-lg"
                  transition={{ type: "spring", stiffness: 400, damping: 30 }}
                />
              )}
              <span className="relative z-10">
                {v === "table" ? "📋 Documents" : "🗂 Schema"}
              </span>
            </button>
          ))}
        </div>
      </motion.div>

      {view === "table" ? (
        <motion.div variants={fade(0.1)} initial="hidden" animate="visible">
          {/* Filters */}
          <div className="flex flex-wrap gap-3 mb-5">
            <div className="relative flex-1 min-w-[200px]">
              <svg className="absolute left-3 top-1/2 -translate-y-1/2 w-4 h-4 text-white/25" fill="none" stroke="currentColor" strokeWidth={2} viewBox="0 0 24 24">
                <circle cx="11" cy="11" r="8" /><line x1="21" y1="21" x2="16.65" y2="16.65" />
              </svg>
              <input
                type="text"
                placeholder="Search by name or email…"
                value={search}
                onChange={(e) => setSearch(e.target.value)}
                className="w-full bg-white/[0.04] border border-white/[0.08] rounded-xl pl-9 pr-4 py-2.5 text-sm text-white placeholder:text-white/25 outline-none focus:border-white/20 transition-colors"
              />
            </div>
            <div className="flex gap-1.5 bg-white/[0.03] border border-white/[0.06] rounded-xl p-1">
              {["all", "active", "pending", "inactive"].map((s) => (
                <button
                  key={s}
                  onClick={() => setStatusFilter(s)}
                  className={`px-3 py-1.5 rounded-lg text-xs font-medium transition-colors capitalize ${
                    statusFilter === s
                      ? "bg-white/[0.1] text-white"
                      : "text-white/40 hover:text-white/60"
                  }`}
                >
                  {s}
                </button>
              ))}
            </div>
          </div>

          {/* Table */}
          <div className="bg-white/[0.02] border border-white/[0.07] rounded-2xl overflow-hidden">
            {/* Header */}
            <div className="grid grid-cols-[1fr_1.5fr_80px_80px_80px] gap-4 px-5 py-3 border-b border-white/[0.06] text-[11px] font-semibold uppercase tracking-widest text-white/25">
              <span>Name</span>
              <span>Email</span>
              <span>Status</span>
              <span>Plan</span>
              <span className="text-right">Revenue</span>
            </div>
            {filtered.length === 0 ? (
              <div className="px-5 py-12 text-center text-white/30 text-sm">No documents match your filter.</div>
            ) : (
              filtered.map((doc, i) => (
                <div
                  key={doc._id}
                  className={`grid grid-cols-[1fr_1.5fr_80px_80px_80px] gap-4 px-5 py-3.5 items-center hover:bg-white/[0.02] transition-colors ${
                    i < filtered.length - 1 ? "border-b border-white/[0.05]" : ""
                  }`}
                >
                  <div>
                    <p className="text-sm font-medium text-white">{doc.name}</p>
                    <p className="text-[10px] text-white/25 font-mono mt-0.5">{doc._id}</p>
                  </div>
                  <p className="text-sm text-white/60 truncate">{doc.email}</p>
                  <span className={`text-[10px] font-semibold px-2 py-0.5 rounded-full text-center capitalize ${STATUS_CLS[doc.status]}`}>
                    {doc.status}
                  </span>
                  <span className={`text-[10px] font-semibold px-2 py-0.5 rounded-full text-center capitalize ${PLAN_CLS[doc.plan]}`}>
                    {doc.plan}
                  </span>
                  <p className={`text-sm font-semibold text-right ${doc.revenue > 0 ? "text-emerald-400" : "text-white/25"}`}>
                    {doc.revenue > 0 ? `$${doc.revenue}` : "—"}
                  </p>
                </div>
              ))
            )}
          </div>

          <p className="text-xs text-white/20 mt-3 text-center">
            Live data will replace this preview once MongoDB Atlas is connected and your cluster is provisioned.
          </p>
        </motion.div>
      ) : (
        /* Schema view */
        <motion.div variants={fade(0.1)} initial="hidden" animate="visible">
          <div className="bg-white/[0.02] border border-white/[0.07] rounded-2xl overflow-hidden">
            <div className="grid grid-cols-[140px_100px_1fr] gap-4 px-5 py-3 border-b border-white/[0.06] text-[11px] font-semibold uppercase tracking-widest text-white/25">
              <span>Field</span>
              <span>Type</span>
              <span>Description</span>
            </div>
            {SCHEMA_FIELDS.map((field, i) => (
              <div
                key={field.field}
                className={`grid grid-cols-[140px_100px_1fr] gap-4 px-5 py-3.5 items-start hover:bg-white/[0.02] transition-colors ${
                  i < SCHEMA_FIELDS.length - 1 ? "border-b border-white/[0.04]" : ""
                }`}
              >
                <code className="text-sm font-mono text-[#FF6B61]">{field.field}</code>
                <span className="text-xs font-semibold text-blue-400 bg-blue-400/10 px-2 py-0.5 rounded-full w-fit">
                  {field.type}
                </span>
                <p className="text-sm text-white/45">{field.note}</p>
              </div>
            ))}
          </div>
          <p className="text-xs text-white/20 mt-3 text-center">
            Schema is customizable — fields will be added or modified to fit your exact business model.
          </p>
        </motion.div>
      )}
    </div>
  );
}
